In [5]:
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple is looking at buying U.K. startup for $1 billion")
print(doc[0].pos_)
print(doc[0].tag_)

PROPN
NNP


In [6]:
import numpy as np

def rgb_to_gray(image):
    im_nor = image / 255.0
    gray = np.dot(im_nor[...,:3], [0.299, 0.587, 0.114])
    return gray

In [10]:
doc =  nlp("Running runs ran was quick")

[tokens.norm_ for tokens in doc]

['running', 'runs', 'ran', 'was', 'quick']

In [1]:
# Your friend has challenged you to a game where are initially at point. P on a mamber line. The challenge is to make exactly X jumps of length Leither in the forward or the backward direction, with the condition that you must minimize the final destination value.

# Your task is to find and return an integer value representing the minimum possible absolute value of the point you can reach after performing exactly X number of jumps.

# Note:

# The goal is to reach a point that is as clase as possible to the origin

# The origin is the position on the number line with the value is O

# Input Specification:

# input1: An integer value P, representing your initial position

# input2: An integer value X, representing the total number of jumps.

# input2: An integer value L, representing the length of each jump.

# Output Specification:

# Retum an integer value representing the minimum possible absolute value of the point you can reach after performing exactly X number of jumps.

class UserMainCode(object):
    @classmethod
    def minimumDistance(cls, P, X, L):
        min_abs = float('inf')
        
            
        

In [ ]:
class UserMainCode(object):
    @classmethod
    def minimumDistance(cls, P, X, L):
        min_abs = float('inf')

        for k in range(X + 1):
            # k is number of forward jumps, (X - k) is number of backward jumps
            pos = P + L * (2 * k - X)
            min_abs = min(min_abs, abs(pos))
        
        return min_abs


In [1]:
#include <stdio.h>

int main() {
    int result[7] = {12, 56, 35, 23, 67, 90, 23};
    int j;

    for (j = 2; j < 6; j++) {
        if (result[j] % 2 == 0)
            printf("%d\n", result[j] * 2);
        else
            printf("%d\n", result[j] * 3);
    }

    return 0;
}


SyntaxError: invalid syntax (2161571968.py, line 3)

In [3]:
from collections import deque

myqueue = deque([i for i in range(10)])  # Creates deque: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

myqueue.append('e')       # Appends 'e' to the right: [0...9, 'e']
myqueue.pop()             # Removes last element ('e')
myqueue.appendleft(10)    # Inserts 10 at the left: [10, 0, 1, ..., 8, 9]
myqueue.popleft()         # Removes 10 from the left

print(myqueue)


deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
def multiply_tuples(tup1, tup2):
    return tuple(a * b for a, b in zip(tup1, tup2))

In [5]:
tuple1 = (2,3)
tuple2 = (4,5)
tuple3 = multiply_tuples(tuple1, tuple2)
print(tuple3)

(8, 15)


In [6]:
checkset = {"a","b","c","b","d"}
set1 = checkset.pop()
print(set1)
print(checkset)



d
{'a', 'b', 'c'}


In [8]:
import itertools
li = [1,2,3,4]
x = itertools.permutations(li)
print(type(x))

<class 'itertools.permutations'>


In [1]:
def k_means_clustering(points: list[tuple[float, float]], k: int, initial_centroids: list[tuple[float, float]],max_iterations: int) -> list[tuple[float, float]]:
	n = len(initial_centroids)
	centroids = initial_centroids.copy()
	for i in range(max_iterations):
		updated_points : list[tuple[int, tuple[float, float]]] = []
		for point in points:
			dist: list[tuple[float, float]] = []
			for j in range(n):
				distance = (point[0] - initial_centroids[j][0])**2 + (point[1] - initial_centroids[j][1])**2
				dist.append((j, distance))
			min_j = min(dist, key=lambda x: x[1])[0]
			updated_points.append((min_j, point))
		final_centroids = []
		for j in range(n):
			sumx = 0
			sumy = 0
			count = 0
			for x in updated_points:
				if x[0] == j:
					sumx += x[1][0]
					sumy += x[1][1]
					count += 1
			if(count > 0):
				final_centroids.append((sumx / count, sumy / count))
			else:
				final_centroids.append(centroids[j])
		centroids = final_centroids
	return final_centroids
    

In [3]:
points = [(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)]
k = 2
initial_centroids = [(1, 1), (10, 1)]
max_iterations = 10

In [4]:
k_means_clustering(points, k, initial_centroids, max_iterations)

[(1.0, 2.0), (10.0, 2.0)]

In [3]:
import numpy as np
from scipy.cluster.hierarchy import linkage

data = np.array([[1, 2], [1, 4], [1, 0],
                 [10, 2], [10, 4]])
link_matrix = linkage(data, method='ward')
link_matrix.shape


(4, 4)

In [5]:
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import CountVectorizer

def cluster_tweets(tweets,k):
    vectorizer = CountVectorizer(lowercase=True,stop_words='english',ngram_range=(1,1))
    X = vectorizer.fit_transform(tweets)
    model = KMeans(n_clusters=k, random_state=42,n_init=10)
    model.fit(X)
    labels = model.labels_
    return labels

In [6]:
tweets = ["Train is delayed", "Train is on time", "I love pizza", "Pizza is delicious"]
k = 2

In [7]:
print(cluster_tweets(tweets,k))

[0 0 1 1]


In [1]:
import numpy as np

data = [28, -27, 24, 7, 15, 26, 29, 20, -31, 6, 14, 56, 91]

data = np.array(data)

mean = np.mean(data)
std = np.std(data)

q3 = np.percentile(data, 75)
q1 = np.percentile(data, 25)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outliers = data[(data < lower_bound) | (data > upper_bound)]

print("Outliers:", outliers)



Outliers: [-27 -31  91]


In [4]:
from sklearn.linear_model import LogisticRegression
import numpy as np
model = LogisticRegression()

X = np.concatenate([
    np.full(80, 1),
    np.full(420, 0)
])
Y = np.concatenate([
    np.full(40, 1),
    np.full(40, 0),
    np.full(300, 1),
    np.full(120, 0)
])
model.fit(X.reshape(-1, 1), Y)

print(model.coef_)
print(model.intercept_)




[[-0.86318297]]
[0.90625126]


In [8]:
w1 = 0.05
w2 = 1
w0 =  -6
e = 2.71828

X1 = 50
X2 = 3.5

sigmoid = 1 / (1 + e ** (-w0 - w1 * X1 - w2 * X2))
print(round(sigmoid, 4))

0.5


In [13]:
from sklearn.metrics import confusion_matrix

y_true = [1,0,2,4]
y_pred = [1,0,1,4]

mat = confusion_matrix(y_true, y_pred)
print(mat.transpose())


[[1 0 0 0]
 [0 1 1 0]
 [0 0 0 0]
 [0 0 0 1]]


In [14]:
n = mat.shape[0]
m = mat.shape[1]
print(n)
print(m)

4
4


In [16]:
precision:list = []
recall:list = []

#sum of elements in a row of mat

for i in range(n):
        precision.append(mat[i][i]/sum(mat[i]))
        recall.append(mat[i][i]/sum(mat[:,i]))

    


C:\Users\user\AppData\Local\Temp\ipykernel_18444\1834591996.py:8: RuntimeWarning: invalid value encountered in scalar divide
  recall.append(mat[i][i]/sum(mat[:,i]))


In [20]:
mat = [[850, 6], [50, 94]]
tp = mat[1][1]
fp = mat[0][1]
tn = mat[0][0]
fn = mat[1][0]

tpr = tp/(tp+fn)
print(tp)
print(fn)

a = 70/75

a

94
50


0.9333333333333333

In [27]:
y_true = [9.91, 12.79, 12.36, 5.31, 4.11]
y_pred = [0.88, 2.6, 0.36, -0.45, 1.64]

from sklearn.metrics import mean_squared_error


mse = 0

mean = np.mean(y_true)

sum = 0
for i in range(len(y_true)):
    mse += (y_true[i] - y_pred[i]) ** 2
    sum += (y_true[i] - mean) ** 2


r_2 = 1 - (sum/mse)

r_2

np.float64(0.8265157579366103)

In [28]:
import numpy as np
def calc_r2(y_true, y_pred):
    
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
   
    
    #Calculate total sum of squares
    tot_ss = 0
    res_ss = 0
    for i in range(len(y_true)):
        tot_ss += (y_true[i] - y_pred[i])**2
        res_ss += (y_true[i] - np.mean(y_true))**2
    
    #Calculate residual sum of squares
     
    
    #Calculate r2
    r2 = 1 - tot_ss/res_ss
    
    return r2.round(2)

In [29]:
calc_r2(y_true, y_pred)

np.float64(-4.76)

In [31]:
import numpy as np
from sklearn.metrics import confusion_matrix
def main():
    # YOUR CODE GOES HERE
    # Please take input and print output to standard input/output (stdin/stdout)
    # E.g. 'input()/raw_input()' for input & 'print' for output
    y_true: list = input()
    y_pred: list = input()
    mat = confusion_matrix(y_true, y_pred)
    n = mat.shape[0]
    m = mat.shape[1]
    precision:list = []
    recall:list = []
    f1_score:list = []
    for i in range(n):
        precision.append(mat[i][i]/sum(mat[i]))
        recall.append(mat[i][i]/sum(mat[:,i]))
        f1_score.append(2 * (precision[i] * recall[i]) / (precision[i] + recall[i]))

    print(f1_score)
    return 0

if __name__ == '__main__':
    main()

InvalidParameterError: The 'y_true' parameter of confusion_matrix must be an array-like. Got '1 0 2' instead.